<%@ Page Title="" Language="C#" UnobtrusiveValidationMode="None" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Lista_Deseos.aspx.cs" Inherits="web.Lista_Deseos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
    <main>
        <div class="showGrid">
            <h2><asp:Label ID="LListado" runat="server" Text ="Lista de deseos" /></h2>
            <asp:GridView ID="GridView1" runat="server" CssClass="grid" AutoGenerateDeleteButton="true" selectedindex="1" onselectedindexchanged="Gridview1_SelectedItemDeleted" HorizontalAlign="Center"></asp:GridView>
        </div>
    </main>
</asp:Content>